export const authActions = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  CHECK_AUTH: "CHECK_AUTH",
  LOGOUT: "LOGOUT",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE"
};

export const taskActions = {
  USER_TASKS_REQUEST: "USER_TASKS_REQUEST",
  USER_TASKS_SUCCESS: "USER_TASKS_SUCCESS",
  USER_TASKS_FAILURE: "USER_TASKS_FAILURE",

  CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
  CREATE_TASKS_SUCCESS: "CREATE_TASKS_SUCCESS",
  CREATE_TASKS_FAILURE: "CREATE_TASKS_FAILURE",

  UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
  UPDATE_TASKS_SUCCESS: "UPDATE_TASKS_SUCCESS",
  UPDATE_TASKS_FAILURE: "UPDATE_TASKS_FAILURE",

  FAV_TASK_REQUEST: "FAV_TASK_REQUEST",
  FAV_TASKS_SUCCESS: "FAV_TASKS_SUCCESS",
  FAV_TASKS_FAILURE: "FAV_TASKS_FAILURE",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASKS_SUCCESS: "DELETE_TASKS_SUCCESS",
  DELETE_TASKS_FAILURE: "DELETE_TASKS_FAILURE",
}
